/**
 * Seeded engine registry: the implementations behind each capability.
 *
 * Quality signals are this project's assessment, not vendor marketing: `resultQuality` is how
 * complete the answer usually is, `reliability` how often the call succeeds, `maintenance` how
 * healthy the upstream project or API is. They only affect ordering — see score.ts §6.
 */

import type { EngineManifest } from '../types.ts';

type Draft = Omit<EngineManifest, 'version' | 'terminal' | 'status'> &
  Partial<Pick<EngineManifest, 'version' | 'terminal' | 'status'>>;

const engine = (draft: Draft): EngineManifest => ({
  version: '1.0.0',
  terminal: false,
  status: 'stable',
  ...draft,
});

export const ENGINES: readonly EngineManifest[] = [
  // -------------------------------------------------------------------------------- identity
  engine({
    id: 'sherlock',
    capability: 'profile-discovery',
    provider: 'sherlock',
    integration: 'sherlock',
    dataFlow: 'network',
    permissions: ['network', 'subprocess'],
    quality: { resultQuality: 0.8, reliability: 0.75, maintenance: 0.95 },
    cost: 'deep',
  }),
  engine({
    id: 'github-api-repos',
    capability: 'repo-discovery',
    provider: 'github',
    integration: 'github',
    dataFlow: 'external-api',
    permissions: ['network'],
    quality: { resultQuality: 0.95, reliability: 0.95, maintenance: 1 },
    cost: 'standard',
  }),
  engine({
    id: 'github-api-analysis',
    capability: 'repo-analysis',
    provider: 'github',
    integration: 'github',
    dataFlow: 'external-api',
    permissions: ['network'],
    quality: { resultQuality: 0.9, reliability: 0.95, maintenance: 1 },
    cost: 'deep',
  }),
  engine({
    id: 'git-clone-analysis',
    capability: 'repo-analysis',
    provider: 'local-runtime',
    dataFlow: 'network',
    permissions: ['network', 'filesystem', 'subprocess'],
    quality: { resultQuality: 0.85, reliability: 0.8, maintenance: 1 },
    cost: 'deep',
  }),
  engine({
    id: 'hibp-api',
    capability: 'breach-exposure',
    provider: 'hibp',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.95, reliability: 0.95, maintenance: 1 },
    cost: 'standard',
  }),
  engine({
    id: 'opensanctions-api',
    capability: 'sanctions-screening',
    provider: 'opensanctions',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.9, reliability: 0.9, maintenance: 0.95 },
    cost: 'standard',
  }),
  engine({
    id: 'opensanctions-local',
    capability: 'sanctions-screening',
    provider: 'opensanctions-dataset',
    dataFlow: 'local',
    permissions: ['filesystem'],
    quality: { resultQuality: 0.85, reliability: 1, maintenance: 0.95 },
    cost: 'fast',
  }),
  engine({
    id: 'wikidata-sparql',
    capability: 'kb-enrichment',
    provider: 'wikidata',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.7, reliability: 0.9, maintenance: 1 },
    cost: 'standard',
  }),

  // -------------------------------------------------------------------------- infrastructure
  engine({
    id: 'doh-resolver',
    capability: 'dns-discovery',
    provider: 'dns-google',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.95, reliability: 0.98, maintenance: 1 },
    cost: 'fast',
  }),
  engine({
    id: 'system-resolver',
    capability: 'dns-discovery',
    provider: 'local-runtime',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.8, reliability: 0.9, maintenance: 1 },
    cost: 'fast',
  }),
  engine({
    id: 'ct-log-search',
    capability: 'subdomain-discovery',
    provider: 'crtsh',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.8, reliability: 0.7, maintenance: 0.8 },
    cost: 'standard',
  }),
  engine({
    id: 'subfinder',
    capability: 'subdomain-discovery',
    provider: 'subfinder',
    integration: 'subfinder',
    dataFlow: 'network',
    permissions: ['network', 'subprocess'],
    quality: { resultQuality: 0.85, reliability: 0.9, maintenance: 0.95 },
    cost: 'standard',
  }),
  engine({
    id: 'amass',
    capability: 'subdomain-discovery',
    provider: 'amass',
    integration: 'amass',
    dataFlow: 'network',
    permissions: ['network', 'subprocess'],
    quality: { resultQuality: 0.95, reliability: 0.85, maintenance: 0.85 },
    cost: 'deep',
  }),
  engine({
    id: 'crtsh-certs',
    capability: 'certificate-discovery',
    provider: 'crtsh',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.85, reliability: 0.7, maintenance: 0.8 },
    cost: 'standard',
  }),
  engine({
    id: 'sslmate-ct',
    capability: 'certificate-discovery',
    provider: 'sslmate',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.9, reliability: 0.95, maintenance: 1 },
    cost: 'standard',
  }),
  engine({
    id: 'local-tls-probe',
    capability: 'certificate-discovery',
    provider: 'local-runtime',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.5, reliability: 0.9, maintenance: 1 },
    cost: 'fast',
  }),
  engine({
    id: 'rdap-lookup',
    capability: 'registration-lookup',
    provider: 'rdap',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.9, reliability: 0.9, maintenance: 1 },
    cost: 'fast',
  }),
  engine({
    id: 'abuseipdb',
    capability: 'ip-reputation',
    provider: 'abuseipdb',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.8, reliability: 0.9, maintenance: 0.9 },
    cost: 'standard',
  }),
  engine({
    id: 'greynoise-community',
    capability: 'ip-reputation',
    provider: 'greynoise',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.75, reliability: 0.9, maintenance: 0.95 },
    cost: 'standard',
  }),
  engine({
    id: 'otx-indicators',
    capability: 'ip-reputation',
    provider: 'otx',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.7, reliability: 0.85, maintenance: 0.8 },
    cost: 'standard',
  }),
  engine({
    id: 'shodan-host',
    capability: 'host-exposure',
    provider: 'shodan',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.9, reliability: 0.9, maintenance: 1 },
    cost: 'standard',
  }),
  engine({
    id: 'censys-host',
    capability: 'host-exposure',
    provider: 'censys',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.9, reliability: 0.9, maintenance: 1 },
    cost: 'standard',
  }),
  engine({
    id: 'ipinfo-lite',
    capability: 'ip-geolocation',
    provider: 'ipinfo',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.75, reliability: 0.95, maintenance: 1 },
    cost: 'fast',
  }),

  // -------------------------------------------------------------------------------------- web
  engine({
    id: 'wayback-cdx',
    capability: 'archive-lookup',
    provider: 'wayback',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.9, reliability: 0.85, maintenance: 0.9 },
    cost: 'standard',
  }),
  engine({
    id: 'common-crawl-index',
    capability: 'archive-lookup',
    provider: 'common-crawl',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.6, reliability: 0.85, maintenance: 0.9 },
    cost: 'deep',
  }),
  engine({
    id: 'urlscan-io',
    capability: 'url-scan',
    provider: 'urlscan',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.9, reliability: 0.9, maintenance: 1 },
    cost: 'deep',
  }),
  engine({
    id: 'brave-search',
    capability: 'web-mentions',
    provider: 'brave-search',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.8, reliability: 0.95, maintenance: 1 },
    cost: 'standard',
  }),
  engine({
    id: 'local-fetch',
    capability: 'page-capture',
    provider: 'local-runtime',
    dataFlow: 'network',
    permissions: ['network', 'filesystem'],
    quality: { resultQuality: 0.7, reliability: 0.85, maintenance: 1 },
    cost: 'standard',
    status: 'beta',
  }),

  // ------------------------------------------------------------------------------------ files
  engine({
    id: 'local-metadata-parser',
    capability: 'file-metadata',
    provider: 'local-runtime',
    dataFlow: 'local',
    permissions: ['filesystem'],
    quality: { resultQuality: 0.9, reliability: 0.95, maintenance: 1 },
    cost: 'fast',
  }),
  engine({
    id: 'local-hasher',
    capability: 'file-hashing',
    provider: 'local-runtime',
    dataFlow: 'local',
    permissions: ['filesystem'],
    quality: { resultQuality: 1, reliability: 1, maintenance: 1 },
    cost: 'fast',
  }),
  engine({
    id: 'virustotal-lookup',
    capability: 'file-reputation',
    provider: 'virustotal',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.95, reliability: 0.9, maintenance: 1 },
    cost: 'standard',
  }),

  // --------------------------------------------------------------------------------- records
  engine({
    id: 'mempool-space',
    capability: 'chain-activity',
    provider: 'mempool-space',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.85, reliability: 0.9, maintenance: 0.95 },
    cost: 'standard',
  }),
  engine({
    id: 'blockchair-api',
    capability: 'chain-activity',
    provider: 'blockchair',
    dataFlow: 'external-api',
    permissions: ['network'],
    quality: { resultQuality: 0.9, reliability: 0.85, maintenance: 0.9 },
    cost: 'standard',
  }),
  engine({
    id: 'etherscan-api',
    capability: 'chain-activity',
    provider: 'etherscan',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.9, reliability: 0.9, maintenance: 1 },
    cost: 'standard',
  }),
  engine({
    id: 'opencorporates-api',
    capability: 'company-lookup',
    provider: 'opencorporates',
    dataFlow: 'external-api',
    permissions: ['network', 'credentials'],
    quality: { resultQuality: 0.9, reliability: 0.9, maintenance: 0.9 },
    cost: 'standard',
  }),
  engine({
    id: 'nominatim-geocode',
    capability: 'geocode',
    provider: 'nominatim',
    dataFlow: 'network',
    permissions: ['network'],
    quality: { resultQuality: 0.8, reliability: 0.85, maintenance: 0.95 },
    cost: 'standard',
  }),

  // ------------------------------------------------------------------------ terminal fallbacks
  // These end every chain (§5). They execute nothing: one opens the source in the browser, the
  // other records what the analyst found by hand. A capability without one is a dead end.
  engine({
    id: 'external-link',
    capability: 'terminal',
    provider: 'external-source',
    dataFlow: 'external-api',
    permissions: ['network', 'browser'],
    quality: { resultQuality: 0.3, reliability: 1, maintenance: 1 },
    cost: 'optional',
    terminal: true,
  }),
  engine({
    id: 'manual-entry',
    capability: 'terminal',
    provider: 'manual',
    dataFlow: 'local',
    permissions: [],
    quality: { resultQuality: 0.3, reliability: 1, maintenance: 1 },
    cost: 'optional',
    terminal: true,
  }),
];
