/**
 * Seeded provider registry. Mirrors `docs/ecosystem/PROVIDER_CATALOG.md`, which carries the
 * rationale and the sources; `catalog.contract.test.ts` fails when the two drift.
 *
 * `lastVerified` is the date the credential/pricing facts were checked against the provider's own
 * documentation. Limits that the documentation did not state are left out rather than guessed.
 * `status` here is the *default* for a fresh workspace; the runtime overrides it from the vault
 * and from live rate-limit headers.
 */

import type { ProviderManifest } from '../types.ts';

export const PROVIDERS: readonly ProviderManifest[] = [
  // ---------------------------------------------------------------- class A: free / open / local
  {
    id: 'local-runtime',
    name: 'Raven local runtime',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'local',
    licence: 'MIT (this project)',
    limits: { note: 'bounded by the sandbox resource caps only' },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: [],
  },
  {
    id: 'manual',
    name: 'Manual entry by the analyst',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'local',
    licence: 'n/a',
    limits: {},
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: [],
  },
  {
    id: 'sherlock',
    name: 'Sherlock',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'free',
    endpoint: 'https://sherlockproject.xyz',
    licence: 'MIT',
    limits: {
      note: 'queries hundreds of sites; rate depends on the target sites, not on Sherlock',
    },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: [],
  },
  {
    id: 'subfinder',
    name: 'ProjectDiscovery subfinder',
    credentialClass: 'A',
    credentials: 'optional',
    pricing: 'free',
    endpoint: 'https://github.com/projectdiscovery/subfinder',
    licence: 'MIT',
    limits: { note: 'runs keyless by default; its own optional sources take their own keys' },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: ['crtsh'],
  },
  {
    id: 'amass',
    name: 'OWASP Amass',
    credentialClass: 'A',
    credentials: 'optional',
    pricing: 'free',
    endpoint: 'https://owasp.org/www-project-amass/',
    licence: 'Apache-2.0',
    limits: { note: 'deep enumeration; minutes per target' },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: ['subfinder'],
  },
  {
    id: 'dns-google',
    name: 'Google Public DNS (DoH)',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'free',
    endpoint: 'https://dns.google/resolve',
    licence: 'public endpoint, provider terms apply',
    limits: { note: 'fair use; no documented per-key quota' },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: ['local-runtime'],
  },
  {
    id: 'rdap',
    name: 'RDAP (IANA bootstrap)',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'free',
    endpoint: 'https://data.iana.org/rdap/dns.json',
    licence: 'open protocol (RFC 9224)',
    limits: { note: 'per-registry throttling; RDAP replaced WHOIS for gTLDs on 2025-01-28' },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: [],
  },
  {
    id: 'crtsh',
    name: 'crt.sh certificate transparency search',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'free',
    endpoint: 'https://crt.sh',
    licence: 'public service, courtesy use',
    limits: { note: 'unofficial service; throttle aggressively and fall back to sslmate' },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: ['sslmate'],
  },
  {
    id: 'wayback',
    name: 'Internet Archive Wayback CDX',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'free',
    endpoint: 'https://web.archive.org/cdx/search/cdx',
    licence: 'Internet Archive terms of use',
    limits: { note: 'no documented public quota; throttle voluntarily' },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: ['common-crawl'],
  },
  {
    id: 'common-crawl',
    name: 'Common Crawl CDXJ index',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'free',
    endpoint: 'https://index.commoncrawl.org',
    licence: 'open data',
    limits: { note: 'index is free to query or download in bulk' },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: ['wayback'],
  },
  {
    id: 'wikidata',
    name: 'Wikidata SPARQL endpoint',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'free',
    endpoint: 'https://query.wikidata.org/sparql',
    licence: 'service terms',
    dataLicence: 'CC0-1.0',
    limits: { note: 'identifying User-Agent required; query timeouts apply' },
    attribution: 'Data from Wikidata (CC0)',
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: [],
  },
  {
    id: 'nominatim',
    name: 'OpenStreetMap Nominatim',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'free',
    endpoint: 'https://nominatim.openstreetmap.org',
    licence: 'OSMF acceptable use policy',
    dataLicence: 'ODbL-1.0',
    limits: {
      requestsPerMinute: 60,
      note: 'absolute maximum 1 request/second, identifying User-Agent, attribution required',
    },
    attribution: '© OpenStreetMap contributors (ODbL)',
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: [],
  },
  {
    id: 'mempool-space',
    name: 'mempool.space',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'free',
    endpoint: 'https://mempool.space/api',
    licence: 'public API, self-hostable',
    limits: { note: 'bitcoin only' },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: ['blockchair'],
  },
  {
    id: 'opensanctions-dataset',
    name: 'OpenSanctions bulk dataset (self-hosted)',
    credentialClass: 'A',
    credentials: 'none',
    pricing: 'local',
    endpoint: 'https://www.opensanctions.org/datasets/',
    licence: 'CC-BY-NC 4.0 for non-commercial use; commercial use needs a licence',
    dataLicence: 'CC-BY-NC-4.0',
    attribution: 'Data from OpenSanctions',
    limits: { note: 'no network calls once the dataset is downloaded' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['opensanctions'],
  },

  // -------------------------------------------------- class B: free public API, token required
  {
    id: 'github',
    name: 'GitHub REST API',
    credentialClass: 'B',
    credentials: 'optional',
    pricing: 'free',
    endpoint: 'https://api.github.com',
    licence: 'GitHub terms of service',
    limits: {
      requestsPerMinute: 1,
      note: '60 requests/hour unauthenticated, 5,000/hour with a token',
    },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['local-runtime'],
  },
  {
    id: 'virustotal',
    name: 'VirusTotal public API',
    credentialClass: 'B',
    credentials: 'required',
    pricing: 'free',
    endpoint: 'https://www.virustotal.com/api/v3',
    licence: 'VirusTotal terms; commercial use requires premium',
    limits: { requestsPerMinute: 4, requestsPerDay: 500 },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: [],
  },
  {
    id: 'abuseipdb',
    name: 'AbuseIPDB',
    credentialClass: 'B',
    credentials: 'required',
    pricing: 'free',
    endpoint: 'https://api.abuseipdb.com/api/v2',
    licence: 'AbuseIPDB terms',
    limits: { note: 'free plan has a daily check quota; exact number unconfirmed' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['greynoise', 'otx'],
  },
  {
    id: 'greynoise',
    name: 'GreyNoise Community API',
    credentialClass: 'B',
    credentials: 'optional',
    pricing: 'free',
    endpoint: 'https://api.greynoise.io/v3/community',
    licence: 'GreyNoise community terms',
    limits: {
      note: '10 lookups/day unauthenticated, 50/week with a free key issued to business email only',
    },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['abuseipdb'],
  },
  {
    id: 'otx',
    name: 'AlienVault OTX',
    credentialClass: 'B',
    credentials: 'required',
    pricing: 'free',
    endpoint: 'https://otx.alienvault.com/api/v1',
    licence: 'OTX terms',
    limits: { note: 'free key; documented limits unconfirmed' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['abuseipdb'],
  },
  {
    id: 'urlscan',
    name: 'urlscan.io',
    credentialClass: 'B',
    credentials: 'required',
    pricing: 'free',
    endpoint: 'https://urlscan.io/api/v1',
    licence: 'urlscan.io terms',
    limits: {
      note: 'per-action minute/hour/day quotas; unauthenticated callers get minor quotas only',
    },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: [],
  },
  {
    id: 'sslmate',
    name: 'SSLMate Certificate Transparency Search',
    credentialClass: 'B',
    credentials: 'required',
    pricing: 'free',
    endpoint: 'https://api.certspotter.com/v1',
    licence: 'SSLMate terms',
    limits: { note: 'free tier: 100 single-hostname queries/hour, 10 full-domain queries/hour' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['crtsh'],
  },
  {
    id: 'ipinfo',
    name: 'IPinfo Lite',
    credentialClass: 'B',
    credentials: 'required',
    pricing: 'free',
    endpoint: 'https://api.ipinfo.io/lite',
    licence: 'IPinfo terms',
    limits: { note: 'free tier with a key; exact quota unconfirmed' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['rdap'],
  },
  {
    id: 'etherscan',
    name: 'Etherscan',
    credentialClass: 'B',
    credentials: 'required',
    pricing: 'free',
    endpoint: 'https://api.etherscan.io/api',
    licence: 'Etherscan terms',
    limits: { note: 'free key tier; exact limits unconfirmed' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['blockchair'],
  },

  // ----------------------------------------------------- class C: free tier of a paid service
  {
    id: 'shodan',
    name: 'Shodan',
    credentialClass: 'C',
    credentials: 'required',
    pricing: 'free-tier',
    endpoint: 'https://api.shodan.io',
    licence: 'Shodan terms',
    limits: {
      note: 'all plans rate-limited to 1 request/second; filtered searches and paging consume query credits',
    },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['censys'],
  },
  {
    id: 'censys',
    name: 'Censys Platform',
    credentialClass: 'C',
    credentials: 'required',
    pricing: 'free-tier',
    endpoint: 'https://api.platform.censys.io',
    licence: 'Censys terms',
    limits: { note: 'Censys Free: 100 credits/month, expiring monthly' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['shodan'],
  },
  {
    id: 'blockchair',
    name: 'Blockchair',
    credentialClass: 'C',
    credentials: 'optional',
    pricing: 'free-tier',
    endpoint: 'https://api.blockchair.com',
    licence: 'Blockchair terms',
    limits: { note: 'free tier without a key; higher limits are paid' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['mempool-space'],
  },
  {
    id: 'brave-search',
    name: 'Brave Search API',
    credentialClass: 'C',
    credentials: 'required',
    pricing: 'free-tier',
    endpoint: 'https://api.search.brave.com/res/v1',
    licence: 'Brave Search API terms',
    limits: {
      note: '$5 of credits per month on the free plan; a credit card is required to register, so this is not credential-free',
    },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: [],
  },
  {
    id: 'opensanctions',
    name: 'OpenSanctions API',
    credentialClass: 'C',
    credentials: 'required',
    pricing: 'free-tier',
    endpoint: 'https://api.opensanctions.org',
    licence: 'free for non-commercial use; businesses need a data licence',
    dataLicence: 'CC-BY-NC-4.0',
    attribution: 'Data from OpenSanctions',
    limits: { note: 'quota depends on the account type' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['opensanctions-dataset'],
  },

  // ------------------------------------------------------------------------ class D: paid only
  {
    id: 'hibp',
    name: 'Have I Been Pwned',
    credentialClass: 'D',
    credentials: 'required',
    pricing: 'paid',
    endpoint: 'https://haveibeenpwned.com/api/v3',
    licence: 'HIBP terms',
    limits: { note: 'email search requires a paid subscription key; only Pwned Passwords is free' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: [],
  },
  {
    id: 'opencorporates',
    name: 'OpenCorporates',
    credentialClass: 'D',
    credentials: 'required',
    pricing: 'paid',
    endpoint: 'https://api.opencorporates.com',
    licence: 'OpenCorporates terms',
    limits: { note: 'self-serve plans start at £2,250/year with monthly call caps' },
    lastVerified: '2026-08-19',
    status: 'not-configured',
    alternatives: ['external-source'],
  },

  // ------------------------------------------------------------------- class E: external only
  {
    id: 'external-source',
    name: 'External source (opened in the browser)',
    credentialClass: 'E',
    credentials: 'none',
    pricing: 'free',
    licence: 'the source\u2019s own terms',
    limits: {
      note: 'Raven opens the source with a prefilled query; nothing is collected automatically',
    },
    lastVerified: '2026-08-19',
    status: 'configured',
    alternatives: [],
  },
];
