/**
 * Seeded transform registry. Mirrors `docs/ecosystem/TRANSFORM_CATALOG.md`.
 *
 * Every chain ends in a terminal engine (`external-link` or `manual-entry`) so a failed provider
 * degrades into "open the source" or "record it by hand" instead of an error.
 */

import type { TransformManifest } from '../types.ts';

type Draft = Omit<TransformManifest, 'version' | 'status' | 'documentation'> &
  Partial<Pick<TransformManifest, 'version' | 'status' | 'documentation'>>;

const transform = (draft: Draft): TransformManifest => ({
  version: '1.0.0',
  status: 'stable',
  documentation: 'docs/ecosystem/TRANSFORM_CATALOG.md',
  ...draft,
});

export const TRANSFORMS: readonly TransformManifest[] = [
  // ------------------------------------------------------------------------ identity & people
  transform({
    id: 'username-to-profiles',
    name: 'Discover public profiles',
    description: 'Checks a username against public sites and returns the profiles that exist.',
    category: 'identity',
    capability: 'profile-discovery',
    inputs: ['username'],
    outputs: ['profile', 'url'],
    engines: ['sherlock', 'manual-entry'],
    priority: 'core',
    cost: 'deep',
    limits: { expectedRuntimeMs: 25_000, maxResults: 60, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 86_400,
  }),
  transform({
    id: 'username-to-repositories',
    name: 'Find repositories',
    description: 'Repositories owned by or associated with the username.',
    category: 'identity',
    capability: 'repo-discovery',
    inputs: ['username', 'profile'],
    outputs: ['repo'],
    engines: ['github-api-repos', 'manual-entry'],
    priority: 'core',
    cost: 'standard',
    limits: { expectedRuntimeMs: 3_000, maxResults: 100, maxInputBatch: 25 },
    cacheable: true,
    cacheTtlSeconds: 3_600,
  }),
  transform({
    id: 'email-to-breaches',
    name: 'Check breach exposure',
    description: 'Known breaches an email address appears in. Requires a paid HIBP subscription.',
    category: 'identity',
    capability: 'breach-exposure',
    inputs: ['email'],
    outputs: ['breach'],
    engines: ['hibp-api', 'external-link'],
    priority: 'optional',
    cost: 'standard',
    limits: { expectedRuntimeMs: 2_000, maxResults: 50, maxInputBatch: 20 },
    cacheable: true,
    cacheTtlSeconds: 86_400,
  }),
  transform({
    id: 'person-to-sanctions',
    name: 'Screen against sanctions and PEP lists',
    description: 'Matches a person or organisation against OpenSanctions data.',
    category: 'records',
    capability: 'sanctions-screening',
    inputs: ['person', 'organization'],
    outputs: ['sanction'],
    engines: ['opensanctions-local', 'opensanctions-api', 'external-link'],
    priority: 'optional',
    cost: 'standard',
    limits: { expectedRuntimeMs: 2_500, maxResults: 25, maxInputBatch: 20 },
    cacheable: true,
    cacheTtlSeconds: 43_200,
  }),
  transform({
    id: 'entity-to-knowledge-base',
    name: 'Enrich from the knowledge base',
    description: 'Structured facts about a person, organisation or place from Wikidata.',
    category: 'analysis',
    capability: 'kb-enrichment',
    inputs: ['person', 'organization', 'place'],
    outputs: ['fact'],
    engines: ['wikidata-sparql', 'external-link'],
    priority: 'recommended',
    cost: 'standard',
    limits: { expectedRuntimeMs: 4_000, maxResults: 40, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 604_800,
  }),

  // ------------------------------------------------------------------------------ infrastructure
  transform({
    id: 'domain-to-dns',
    name: 'Discover DNS records',
    description: 'A, AAAA, MX, NS, TXT and CNAME records for a domain or hostname.',
    category: 'infrastructure',
    capability: 'dns-discovery',
    inputs: ['domain', 'hostname'],
    outputs: ['dns_record', 'ip', 'hostname'],
    engines: ['doh-resolver', 'system-resolver', 'manual-entry'],
    priority: 'core',
    cost: 'fast',
    limits: { expectedRuntimeMs: 800, maxResults: 40, maxInputBatch: 50 },
    cacheable: true,
    cacheTtlSeconds: 900,
  }),
  transform({
    id: 'domain-to-subdomains',
    name: 'Discover subdomains',
    description: 'Passive subdomain enumeration from certificate transparency and OSINT sources.',
    category: 'infrastructure',
    capability: 'subdomain-discovery',
    inputs: ['domain'],
    outputs: ['hostname'],
    engines: ['ct-log-search', 'subfinder', 'amass', 'manual-entry'],
    priority: 'core',
    cost: 'deep',
    limits: { expectedRuntimeMs: 20_000, maxResults: 200, maxInputBatch: 5 },
    cacheable: true,
    cacheTtlSeconds: 21_600,
  }),
  transform({
    id: 'domain-to-certificates',
    name: 'Discover certificates',
    description: 'Certificates issued for a domain, from certificate transparency logs.',
    category: 'infrastructure',
    capability: 'certificate-discovery',
    inputs: ['domain', 'hostname'],
    outputs: ['certificate', 'hostname'],
    engines: ['crtsh-certs', 'sslmate-ct', 'local-tls-probe', 'manual-entry'],
    priority: 'core',
    cost: 'standard',
    limits: { expectedRuntimeMs: 5_000, maxResults: 100, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 21_600,
  }),
  transform({
    id: 'domain-to-registration',
    name: 'Look up registration data',
    description: 'RDAP registration record for a domain: registrar, dates, contacts, status.',
    category: 'infrastructure',
    capability: 'registration-lookup',
    inputs: ['domain'],
    outputs: ['organization', 'person', 'fact'],
    engines: ['rdap-lookup', 'external-link'],
    priority: 'core',
    cost: 'fast',
    limits: { expectedRuntimeMs: 1_200, maxResults: 15, maxInputBatch: 30 },
    cacheable: true,
    cacheTtlSeconds: 86_400,
  }),
  transform({
    id: 'ip-to-registration',
    name: 'Look up network registration',
    description: 'RDAP record for an IP or ASN: allocation, holder, abuse contacts.',
    category: 'infrastructure',
    capability: 'registration-lookup',
    inputs: ['ip', 'asn'],
    outputs: ['asn', 'organization', 'fact'],
    engines: ['rdap-lookup', 'external-link'],
    priority: 'core',
    cost: 'fast',
    limits: { expectedRuntimeMs: 1_200, maxResults: 15, maxInputBatch: 30 },
    cacheable: true,
    cacheTtlSeconds: 86_400,
  }),
  transform({
    id: 'ip-to-reputation',
    name: 'Check IP reputation',
    description: 'Abuse reports and background-noise classification for an IP address.',
    category: 'infrastructure',
    capability: 'ip-reputation',
    inputs: ['ip'],
    outputs: ['reputation'],
    engines: ['abuseipdb', 'greynoise-community', 'otx-indicators', 'external-link'],
    priority: 'recommended',
    cost: 'standard',
    limits: { expectedRuntimeMs: 2_000, maxResults: 10, maxInputBatch: 25 },
    cacheable: true,
    cacheTtlSeconds: 3_600,
  }),
  transform({
    id: 'ip-to-exposure',
    name: 'Find exposed services',
    description: 'Open ports and service banners recorded by internet-wide scanners.',
    category: 'infrastructure',
    capability: 'host-exposure',
    inputs: ['ip', 'hostname'],
    outputs: ['service', 'certificate'],
    engines: ['shodan-host', 'censys-host', 'external-link'],
    priority: 'recommended',
    cost: 'standard',
    limits: { expectedRuntimeMs: 3_000, maxResults: 50, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 7_200,
  }),
  transform({
    id: 'ip-to-network-context',
    name: 'Resolve network context',
    description: 'ASN, network owner and coarse location for an IP address.',
    category: 'infrastructure',
    capability: 'ip-geolocation',
    inputs: ['ip'],
    outputs: ['asn', 'place'],
    engines: ['ipinfo-lite', 'external-link'],
    priority: 'recommended',
    cost: 'fast',
    limits: { expectedRuntimeMs: 900, maxResults: 5, maxInputBatch: 50 },
    cacheable: true,
    cacheTtlSeconds: 86_400,
  }),

  // ------------------------------------------------------------------------------ web & content
  transform({
    id: 'url-to-archive-snapshots',
    name: 'Find archived snapshots',
    description: 'Historical captures of a URL or domain from web archives.',
    category: 'web',
    capability: 'archive-lookup',
    inputs: ['url', 'domain'],
    outputs: ['snapshot'],
    engines: ['wayback-cdx', 'common-crawl-index', 'external-link'],
    priority: 'core',
    cost: 'standard',
    limits: { expectedRuntimeMs: 4_000, maxResults: 100, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 86_400,
  }),
  transform({
    id: 'url-to-scan',
    name: 'Scan the page',
    description: 'Submits a URL for scanning and returns the resolved hosts, IPs and verdicts.',
    category: 'web',
    capability: 'url-scan',
    inputs: ['url'],
    outputs: ['scan', 'ip', 'domain'],
    engines: ['urlscan-io', 'external-link'],
    priority: 'recommended',
    cost: 'deep',
    limits: { expectedRuntimeMs: 30_000, maxResults: 30, maxInputBatch: 5 },
    cacheable: true,
    cacheTtlSeconds: 3_600,
  }),
  transform({
    id: 'selector-to-web-mentions',
    name: 'Search web mentions',
    description: 'Public web results mentioning the selector.',
    category: 'web',
    capability: 'web-mentions',
    inputs: ['username', 'email', 'domain', 'organization', 'person'],
    outputs: ['url'],
    engines: ['brave-search', 'external-link'],
    priority: 'recommended',
    cost: 'standard',
    limits: { expectedRuntimeMs: 2_500, maxResults: 40, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 3_600,
  }),
  transform({
    id: 'url-to-page-capture',
    name: 'Capture the page',
    description: 'Fetches a page in the sandbox and stores it as evidence.',
    category: 'web',
    capability: 'page-capture',
    inputs: ['url'],
    outputs: ['file', 'note'],
    engines: ['local-fetch', 'manual-entry'],
    priority: 'experimental',
    cost: 'standard',
    limits: { expectedRuntimeMs: 8_000, maxResults: 2, maxInputBatch: 10 },
    cacheable: false,
    status: 'beta',
  }),

  // ------------------------------------------------------------------------- files & artefacts
  transform({
    id: 'file-to-metadata',
    name: 'Extract file metadata',
    description: 'Embedded metadata of a local file: authors, timestamps, device, coordinates.',
    category: 'files',
    capability: 'file-metadata',
    inputs: ['file'],
    outputs: ['metadata', 'person', 'place', 'device'],
    engines: ['local-metadata-parser', 'manual-entry'],
    priority: 'core',
    cost: 'fast',
    limits: { expectedRuntimeMs: 400, maxResults: 30, maxInputBatch: 50 },
    cacheable: false,
  }),
  transform({
    id: 'file-to-hashes',
    name: 'Compute hashes',
    description: 'SHA-256 and related digests of a local file.',
    category: 'files',
    capability: 'file-hashing',
    inputs: ['file'],
    outputs: ['hash'],
    engines: ['local-hasher', 'manual-entry'],
    priority: 'core',
    cost: 'fast',
    limits: { expectedRuntimeMs: 300, maxResults: 4, maxInputBatch: 100 },
    cacheable: false,
  }),
  transform({
    id: 'hash-to-reputation',
    name: 'Check file reputation',
    description: 'Anti-malware verdicts for a file hash. Sends only the hash, never the file.',
    category: 'files',
    capability: 'file-reputation',
    inputs: ['hash'],
    outputs: ['verdict'],
    engines: ['virustotal-lookup', 'external-link'],
    priority: 'recommended',
    cost: 'standard',
    limits: { expectedRuntimeMs: 2_000, maxResults: 5, maxInputBatch: 4 },
    cacheable: true,
    cacheTtlSeconds: 86_400,
  }),

  // ------------------------------------------------------------------------------- repositories
  transform({
    id: 'repository-to-analysis',
    name: 'Analyse the repository',
    description: 'Languages, dependencies, releases and activity of a repository.',
    category: 'repositories',
    capability: 'repo-analysis',
    inputs: ['repo'],
    outputs: ['language', 'dependency', 'release'],
    engines: ['github-api-analysis', 'git-clone-analysis', 'manual-entry'],
    priority: 'core',
    cost: 'deep',
    limits: { expectedRuntimeMs: 15_000, maxResults: 120, maxInputBatch: 5 },
    cacheable: true,
    cacheTtlSeconds: 3_600,
  }),
  transform({
    id: 'repository-to-contributors',
    name: 'Find contributors',
    description: 'People and accounts that contributed to a repository.',
    category: 'repositories',
    capability: 'repo-analysis',
    inputs: ['repo'],
    outputs: ['person', 'username', 'email'],
    engines: ['github-api-analysis', 'git-clone-analysis', 'manual-entry'],
    priority: 'recommended',
    cost: 'standard',
    limits: { expectedRuntimeMs: 4_000, maxResults: 100, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 3_600,
  }),
  transform({
    id: 'repository-to-related',
    name: 'Find related repositories',
    description: 'Forks, sibling projects and repositories sharing contributors.',
    category: 'repositories',
    capability: 'repo-discovery',
    inputs: ['repo'],
    outputs: ['repo'],
    engines: ['github-api-repos', 'manual-entry'],
    priority: 'optional',
    cost: 'standard',
    limits: { expectedRuntimeMs: 4_000, maxResults: 50, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 3_600,
  }),

  // -------------------------------------------------------------- financial & public records
  transform({
    id: 'crypto-address-to-activity',
    name: 'Analyse chain activity',
    description: 'Transactions and counterparties of a public blockchain address.',
    category: 'records',
    capability: 'chain-activity',
    inputs: ['crypto_address'],
    outputs: ['transaction', 'crypto_address'],
    engines: ['mempool-space', 'blockchair-api', 'etherscan-api', 'external-link'],
    priority: 'optional',
    cost: 'standard',
    limits: { expectedRuntimeMs: 3_500, maxResults: 100, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 900,
  }),
  transform({
    id: 'organization-to-registry',
    name: 'Look up the company registry',
    description: 'Company registration data. Requires a paid provider; otherwise links out.',
    category: 'records',
    capability: 'company-lookup',
    inputs: ['organization', 'company'],
    outputs: ['company', 'person'],
    engines: ['opencorporates-api', 'external-link'],
    priority: 'external',
    cost: 'standard',
    limits: { expectedRuntimeMs: 3_000, maxResults: 25, maxInputBatch: 10 },
    cacheable: true,
    cacheTtlSeconds: 604_800,
  }),
  transform({
    id: 'place-to-coordinates',
    name: 'Resolve a place',
    description: 'Coordinates and administrative context for a place name or address.',
    category: 'records',
    capability: 'geocode',
    inputs: ['place'],
    outputs: ['coordinates'],
    engines: ['nominatim-geocode', 'external-link'],
    priority: 'optional',
    cost: 'standard',
    limits: { expectedRuntimeMs: 1_500, maxResults: 10, maxInputBatch: 5 },
    cacheable: true,
    cacheTtlSeconds: 604_800,
  }),
];
