/**
 * Stage 8 — the Applier (10_INTEGRATIONS.md §3.8).
 *
 * This is the *only* path from a tool result into the graph (N4, R3). It runs client-side against
 * the local Y.Doc and does all of its work inside one `tx(doc, 'local:proposal-apply', …)`, so an
 * import — however many nodes, edges and field patches it carries — is exactly one undo step (N3).
 * Yjs transactions are re-entrant, so the domain mutation helpers called inside the callback join
 * this transaction instead of opening their own.
 */

import type * as Y from 'yjs';

import {
  addEdges,
  addNodes,
  findFreePlacement,
  getNode,
  listNodes,
  makeEdge,
  makeNode,
  tx,
  updateNode,
  type BoardEdge,
  type BoardNode,
  type Provenance as DomainProvenance,
} from '@nexus/domain';

import { IntegrationError } from './errors.ts';
import { bucketOf } from './extract/confidence.ts';
import type {
  ConflictItem,
  EnrichItem,
  FieldPatch,
  ImportProposal,
  NewEdgeItem,
  NewNodeItem,
  NodeRefOrTemp,
  Provenance,
} from './pipeline.ts';
import { PROVENANCE_EXCERPT_LIMIT } from './pipeline.ts';
import { IDENTITY_KEY_PROP, PROVENANCE_PROP } from './resolve/identity.ts';

export interface ApplyOptions {
  readonly selectedItemIds: readonly string[];
  readonly conflictResolutions: Readonly<Record<string, 'keep' | 'replace' | 'keep_both'>>;
  readonly placement: 'radial' | 'grid' | 'manual';
  /** Node ids are generated by the caller so the client can pre-compute the ghost preview. */
  readonly newId: () => string;
  readonly now: string;
  /** Items already applied from this proposal; re-applying one is a no-op (§3.8 point 4). */
  readonly alreadyApplied?: Readonly<Record<string, string>>;
  /** Where the radial layout is centred; defaults to the anchor node or the origin. */
  readonly origin?: { readonly x: number; readonly y: number };
}

export interface ApplyResult {
  readonly createdNodeIds: readonly string[];
  readonly createdEdgeIds: readonly string[];
  readonly patchedNodeIds: readonly string[];
  readonly undoStackEntryId: string;
  readonly skipped: readonly { itemId: string; reason: string }[];
  /** tempId → real node id, persisted on the proposal row so a re-run can diff (§3.8 point 2). */
  readonly tempIdMap: Readonly<Record<string, string>>;
  readonly label: string;
}

/** Ring radius `180 + ring * 140`, angular slot `2π / max(6, count)` (05_CANVAS_ENGINE.md §9.3). */
export function radialPosition(
  origin: { x: number; y: number },
  ring: number,
  index: number,
  count: number,
): { x: number; y: number } {
  const radius = 180 + ring * 140;
  const slots = Math.max(6, count);
  const angle = (2 * Math.PI * index) / slots;
  return { x: origin.x + Math.cos(angle) * radius, y: origin.y + Math.sin(angle) * radius };
}

function toDomainProvenance(provenance: Provenance): DomainProvenance {
  return {
    kind: 'tool',
    source: provenance.source,
    tool: provenance.tool,
    runId: provenance.runId,
    proposalId: null,
    rawRef: provenance.artifactRef?.key ?? null,
    observedAt: provenance.observedAt,
    importedAt: provenance.importedAt,
    actorId: provenance.actorUserId,
    confidence: bucketOf(provenance.confidence),
  };
}

function withExcerpt(provenance: Provenance, excerpt: unknown): Provenance {
  const text = JSON.stringify(excerpt ?? null) ?? 'null';
  return { ...provenance, excerpt: text.slice(0, PROVENANCE_EXCERPT_LIMIT) };
}

function appendProvenance(
  props: Readonly<Record<string, unknown>>,
  provenance: Provenance,
): unknown[] {
  const existing = props[PROVENANCE_PROP];
  const list: unknown[] = Array.isArray(existing) ? [...(existing as unknown[])] : [];
  list.push(provenance);
  // Capped at 50 entries, oldest collapsed with a count (§8.3).
  if (list.length > 50) {
    const dropped = list.length - 50;
    return [{ collapsed: dropped }, ...list.slice(dropped)];
  }
  return list;
}

function applyPatch(props: Record<string, unknown>, patch: FieldPatch): void {
  const field = patch.path.replace(/^\//, '');
  if (patch.op === 'set') {
    props[field] = patch.value;
    return;
  }
  const current = props[field];
  const list: unknown[] = Array.isArray(current)
    ? [...(current as unknown[])]
    : current === undefined || current === null
      ? []
      : [current];
  if (
    patch.op === 'addToSet' &&
    list.some((item) => JSON.stringify(item) === JSON.stringify(patch.value))
  ) {
    return;
  }
  list.push(patch.value);
  props[field] = list;
}

/**
 * Applies the selected items of a proposal. Every refusal is reported in `skipped` — nothing is
 * dropped quietly, because "we imported 12 of your 14 items and did not say so" is the failure mode
 * that destroys trust in an import tool.
 */
export function applyProposal(
  doc: Y.Doc,
  proposal: ImportProposal,
  options: ApplyOptions,
): ApplyResult {
  if (Date.parse(proposal.expiresAt) <= Date.parse(options.now)) {
    throw new IntegrationError('PROPOSAL_EXPIRED', { runId: proposal.runId });
  }

  const selected = new Set(options.selectedItemIds);
  const applied = options.alreadyApplied ?? {};
  const skipped: { itemId: string; reason: string }[] = [];
  const createdNodeIds: string[] = [];
  const createdEdgeIds: string[] = [];
  const patchedNodeIds: string[] = [];
  const tempIdMap: Record<string, string> = { ...applied };

  const nodeItems = proposal.items.filter(
    (item): item is NewNodeItem =>
      item.kind === 'new_node' && selected.has(item.id) && applied[item.id] === undefined,
  );
  const edgeItems = proposal.items.filter(
    (item): item is NewEdgeItem => item.kind === 'new_edge' && selected.has(item.id),
  );
  const enrichItems = proposal.items.filter(
    (item): item is EnrichItem => item.kind === 'enrich' && selected.has(item.id),
  );
  const conflictItems = proposal.items.filter(
    (item): item is ConflictItem => item.kind === 'conflict' && selected.has(item.id),
  );

  for (const item of nodeItems) {
    if (item.node.provenance.tool === '' || item.node.provenance.runId === '') {
      throw new IntegrationError('PROVENANCE_MISSING', {
        runId: proposal.runId,
        detail: { itemId: item.id },
      });
    }
  }

  const anchor = options.origin ?? anchorOrigin(doc, nodeItems);
  const occupied = listNodes(doc).map((node) => ({ x: node.x, y: node.y, w: node.w, h: node.h }));

  const newNodes: BoardNode[] = [];
  nodeItems.forEach((item, index) => {
    const id = options.newId();
    tempIdMap[item.node.tempId] = id;
    const desired =
      options.placement === 'radial'
        ? radialPosition(
            anchor,
            item.node.layoutHint?.ring ?? 1,
            item.node.layoutHint?.index ?? index,
            nodeItems.length,
          )
        : { x: anchor.x + (index % 5) * 320, y: anchor.y + Math.floor(index / 5) * 220 };
    // Imports never move existing nodes: the placer spirals outward instead (§9).
    const position = findFreePlacement({
      desired,
      size: { w: 280, h: 160 },
      occupied,
      maxRings: 60,
    });
    occupied.push({ ...position, w: 280, h: 160 });

    const provenance = withExcerpt(item.node.provenance, item.node.props);
    newNodes.push(
      makeNode(
        {
          id,
          type: item.node.nodeType,
          x: position.x,
          y: position.y,
          title: item.node.title,
          tags: [...item.node.tags],
          data: {
            ...item.node.props,
            [IDENTITY_KEY_PROP]: item.node.identityKey,
            [PROVENANCE_PROP]: [provenance],
          },
          provenance: toDomainProvenance(provenance),
        },
        options.now,
      ),
    );
    createdNodeIds.push(id);
  });

  const newEdges: BoardEdge[] = [];
  for (const item of edgeItems) {
    if (applied[item.id] !== undefined) continue;
    const from = resolveRef(item.edge.fromRef, tempIdMap, doc);
    const to = resolveRef(item.edge.toRef, tempIdMap, doc);
    if (from === undefined || to === undefined) {
      skipped.push({ itemId: item.id, reason: 'target_missing' });
      continue;
    }
    const id = options.newId();
    tempIdMap[item.edge.tempId] = id;
    const provenance = withExcerpt(item.edge.provenance, item.edge.props);
    newEdges.push(
      makeEdge(
        {
          id,
          from,
          to,
          type: item.edge.edgeType,
          ...(item.edge.label === undefined ? {} : { label: item.edge.label }),
          provenance: toDomainProvenance(provenance),
        },
        options.now,
      ),
    );
    createdEdgeIds.push(id);
  }

  const patches = new Map<string, Record<string, unknown>>();

  for (const item of enrichItems) {
    if (applied[item.id] !== undefined) continue;
    const target = getNode(doc, item.targetNodeId);
    if (target === undefined) {
      skipped.push({ itemId: item.id, reason: 'target_missing' });
      continue;
    }
    const data = { ...(patches.get(item.targetNodeId) ?? target.data) };
    for (const patch of item.fieldPatches) applyPatch(data, patch);
    data[PROVENANCE_PROP] = appendProvenance(data, withExcerpt(item.provenance, item.fieldPatches));
    patches.set(item.targetNodeId, data);
  }

  for (const item of conflictItems) {
    if (applied[item.id] !== undefined) continue;
    const resolution = options.conflictResolutions[item.id] ?? item.resolution;
    const target = getNode(doc, item.targetNodeId);
    if (target === undefined) {
      skipped.push({ itemId: item.id, reason: 'target_missing' });
      continue;
    }
    if (resolution === 'keep') {
      skipped.push({ itemId: item.id, reason: 'kept_existing' });
      continue;
    }
    const data = { ...(patches.get(item.targetNodeId) ?? target.data) };
    if (resolution === 'replace') {
      data[item.field] = item.incomingValue;
    } else {
      applyPatch(data, { path: `/${item.field}`, op: 'addToSet', value: item.incomingValue });
    }
    data[PROVENANCE_PROP] = appendProvenance(
      data,
      withExcerpt(item.incomingProvenance, item.incomingValue),
    );
    patches.set(item.targetNodeId, data);
  }

  const label = `Import from ${proposal.integrationId} (${String(
    createdNodeIds.length + createdEdgeIds.length + patches.size,
  )} items)`;

  // One transaction: one undo step (N3, §3.8 point 1).
  tx(doc, 'local:proposal-apply', () => {
    if (newNodes.length > 0)
      addNodes(doc, newNodes, { origin: 'local:proposal-apply', now: options.now });
    if (newEdges.length > 0)
      addEdges(doc, newEdges, { origin: 'local:proposal-apply', now: options.now });
    for (const [nodeId, data] of patches) {
      const ok = updateNode(
        doc,
        nodeId,
        { data },
        { origin: 'local:proposal-apply', now: options.now },
      );
      if (ok) patchedNodeIds.push(nodeId);
    }
  });

  return {
    createdNodeIds,
    createdEdgeIds,
    patchedNodeIds,
    undoStackEntryId: `${proposal.id}:${options.now}`,
    skipped,
    tempIdMap,
    label,
  };
}

function anchorOrigin(doc: Y.Doc, items: readonly NewNodeItem[]): { x: number; y: number } {
  const anchorId = items.find((item) => item.node.layoutHint?.anchorNodeId !== undefined)?.node
    .layoutHint?.anchorNodeId;
  if (anchorId !== undefined) {
    const anchorNode = getNode(doc, anchorId);
    if (anchorNode !== undefined) return { x: anchorNode.x, y: anchorNode.y };
  }
  return { x: 0, y: 0 };
}

function resolveRef(
  ref: NodeRefOrTemp,
  tempIdMap: Readonly<Record<string, string>>,
  doc: Y.Doc,
): string | undefined {
  if (ref.kind === 'existing')
    return getNode(doc, ref.nodeId) === undefined ? undefined : ref.nodeId;
  return tempIdMap[ref.tempId];
}
